### ISSUE TITLE
JOSS Review: paper - summary

### ISSUE THREAD

**Issue by njtierney** [Tpatni719/gsMAMS#11]
> Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?

Currently the summary does not describe the purpose of the software for a non-specialist audience:

> A multi-arm trial allows simultaneous comparison of multiple experimental treatments with a common control and provides a substantial efficiency advantage compared to conventional randomized controlled trial. A multi-stage trial allows multiple interim looks at the trial outcome so that the ineffective arm can be stopped early. In the current R ecosystem, `MAMS` @Jaki2019 is one of the few packages that can handle multiple stages, multiple treatment arms and different types of endpoints but the computational effort of obtaining sample size and sequential stopping boundaries is very high when the number of stages exceeds 3. More importantly, their method may lead to under powered study when the endpoint is time to event data. Therefore, we introduce the R package `gsMAMS` for designing group sequential multi-arm multi-satge (MAMS) trials with continuous, ordinal and survival outcomes which is computationally very efficient even for number of stages greater than 3. We also discuss the applications of the package.          

I think this could be improved by adding sentences like the following

> The `gsMAMS` software facilitates the design and planning of clinical trials, specifically focussing on trials that have multiple treatment arms. It is intended to be used by <insert audience>, so that they can determine <specific features that this audience would like to use these functions for>. Compared to conventional randomized control trials or single arm trials, multi-arm trials allow...

**Comment by Tpatni719** [comment]
I have added the details.

**Comment by njtierney** [comment]
As stated in #13 - could you please provide the details that you added into this issue thread, so that I can specifically see how you have addressed this?

**Comment by Tpatni123** [comment]
![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/bddca60e-9804-4587-bbc6-d9bdffe0e6ab)

**Comment by njtierney** [comment]
Thanks!
