### ISSUE TITLE
JOSS Review: paper - statement of need

### ISSUE THREAD

**Issue by njtierney** [Tpatni719/gsMAMS#12]
> Does the paper have a section titled 'Statement of need' that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?

The authors provide a great summary of the statement of need, but I think that this could be improved in a couple of ways.

> Some packages that are available in R have limitations either in the number of treatment arms that can be incorporated in the package, the number of interim analyses that can be implemented in the package, or the different kinds of outcomes that the package can handle, but the `MAMS` package works well both for multiple treatment arms and multiple stages.

- This is a very long sentence, I would recommend breaking this up into at least 2 sentences
- cite the `MAMS` package here in its first usage
- Cite the other packages that are available in R that can be used in this space - it sounds like there are other packages beyond MAMS?

The authors should also state the target audience in this section.

Could the authors also describe why the package is named `gsMAMS`? What does the `gs` stand for? And for that matter, what does the `MAMS` stand for? Multiple Arm MS?

**Comment by Tpatni719** [comment]
Thank you for the suggestions!
The citation for MAMS is being provided in the summary itself and I have cited the other packages. I have also included the statement regarding target audience. And lastly, the gsMAMS is described in the summary itself. Please see the snapshot below:
![image](https://github.com/Tpatni719/gsMAMS/assets/13623648/06776676-e625-4466-a237-62acd39157e1)

**Comment by njtierney** [comment]
Thanks! I note that you have a typo here: "satge" --> "stage"

I suggest adding (emphasis mine)

The R package, `gdMAMS`, _which is an acronym, standing for_: **g**roup **s**equential **m**ulti-**a**rm **m**ulti-**s**tage (MAMS) trials.

**Comment by Tpatni123** [comment]
![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/cf49492f-8569-4ea4-9a33-91c468dd1fdb)

Regarding target audience

![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/640ccec3-450e-40bf-aedb-82de70005435)

**Comment by njtierney** [comment]
Thanks!
