### ISSUE TITLE
JOSS Review: paper - state of the field

### ISSUE THREAD

**Issue by njtierney** [Tpatni719/gsMAMS#13]
> Do the authors describe how this software compares to other commonly-used packages?

They do! But I think that this could be improved a little bit. The authors state the following about MAMS:

> But the computational effort of obtaining stopping boundaries is very high when the number of stages exceeds 3. This is the major hurdle of using `MAMS` package.

I think it would be beneficial to show one usage of the MAMS package or describe in more detail, perhaps using code, what the specific issues are - I note that the authors state:

> To give an example, the computational time of `MAMS` package to obtain stopping boundaries and sample size of a multi-arm trial for continuous outcome with four experimental arms and three stages is around 7 minutes and for four stages is around 4.5 hours. But for `gsMAMS` package with same trial configuration, the computational time to obtain stopping boundaries and sample size for three stages and four stages design is around 0.06 seconds for both the cases.

Which is great! But it would be even better if they can demonstrate what the `MAMS` code looks like, compared to the `gsMAMS` code, and perhaps present these results they they have shown above in a table, to clearly demonstrate to the reader the advantage that `gsMAMS` provides?

**Comment by Tpatni719** [comment]
I have added an example demonstration in the paper.

**Comment by njtierney** [comment]
When you respond to these issues on the paper could you please paste the content that you have added which addresses it, into the issue? This will save me needing to scour the paper to see where these changes were made. Thanks!

**Comment by Tpatni123** [comment]
Sure!!
![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/de3f56e5-a392-4756-be0f-6fde684e1eb2)

**Comment by njtierney** [comment]
Thanks for this - would you be able to perhaps use comparable parameter values for the `mams` and `design_cont` functions?

**Comment by Tpatni123** [comment]
I have used same trial configuration/parameters for both functions.

**Comment by njtierney** [comment]
Ah sorry it was hard to compare the code - could you add a sentence stating that the same equivalent parameters in each are used?

**Comment by Tpatni719** [comment]
I have added the sentence.

**Comment by njtierney** [comment]
What sentence did you add? Can you please respond to comments with the additions that you made?

**Comment by Tpatni123** [comment]
![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/aadbc44e-8584-4288-ba9b-16b56adbd290)

**Comment by njtierney** [comment]
OK great, thanks!
