### ISSUE TITLE
JOSS Review: Paper - use rmarkdown not plain markdown only for formatting

### ISSUE THREAD

**Issue by njtierney** [Tpatni719/gsMAMS#16]
Would you be able to render this as an rmarkdown document instead of plain markdown, as you have done for the vignette?

**Comment by Tpatni123** [comment]
Are you talking about the paper.md file? I had checked other submitted papers and they were in plain markdown.

**Comment by njtierney** [comment]
They are in plain markdown, but you have several sections of R code that you have copied and pasted, which has led to several errors, due to a change in syntax from other changes, and also in referring to numbers that are not the same as the numbers presented in the text. Using an rmarkdown document would solve these reproducibility problems.

**Comment by Tpatni123** [comment]
I will update the syntax regarding hazard ratios, but the numbers are correct as I have just checked them and I think you haven't set the seed which I have mentioned in the paper. Please see the snaphot below. I have replicated the results for survival outcome.
![image](https://github.com/Tpatni719/gsMAMS/assets/42519735/c624e7c7-9d51-4bc3-a2ec-6bcd19d8286c)

**Comment by njtierney** [comment]
My suggestion was that using rmarkdown will save you needing to update the numbers manually and improve reproducibility. Is this something that you see yourself doing? If not, please feel free to close the issue, I am suggesting this because I think it will improve reproducibility in your work
