### ISSUE TITLE
set.seed( ) & results of example code

### ISSUE THREAD

**Issue by RhysPeploe** [Tpatni719/gsMAMS#3]
https://github.com/openjournals/joss-reviews/issues/6322

My understanding is that these functions are deterministic, does the seed affect the results? If the seed does not imapct results, this can be removed? 

It would be good to report the results you get from the code in the paper so that users can compare their results to those in the paper too

**Comment by Tpatni719** [comment]
The design functions of the trial are indeed deterministic, but for generating the operating characteristics of the trial, we need the seed for reproducibility.

**Comment by RhysPeploe** [comment]
Ahh very well! Then I do not have concern with the seed. The results would be a good extra but that will not stop the checklist being completed - thanks
