### ISSUE TITLE
JOSS Review: Functionality: Have the functional claims of the software been confirmed?

### ISSUE THREAD

**Issue by njtierney** [Tpatni719/gsMAMS#6]
I think that to demonstrate the functional claims of the software there should be a short form vignette which describes how this software solves a problem, and work through how you would expect a user to use this software.

See the [vignettes chapter](https://r-pkgs.org/vignettes.html) in the R packages book for more details on this.

Review link: https://github.com/openjournals/joss-reviews/issues/6322

**Comment by Tpatni719** [comment]
In the paper, we have provided comprehensive examples explaining each argument of every function so that the user can easily use the package based on these examples.

**Comment by njtierney** [comment]
I think that the paper should be turned into a vignette as well. The paper.md will not be shipped with the package.

> In the paper, we have provided comprehensive examples explaining each argument of every function so that the user can easily use the package based on these examples.

Have you read the [vignette](https://r-pkgs.org/vignettes.html) chapter of the R Packages book? This provides examples of how to create a vignette. In addition this will provide the output of the code that you use.

**Comment by Tpatni123** [comment]
Thanks for the link! I will add the vignette.

**Comment by Tpatni719** [comment]
I have added the vignette.

**Comment by Tpatni123** [comment]
And if in case you might want to create the vignette, it will take a LOT of time because the number of simulations is very high. So, I just wanted to give you a heads-up.

**Comment by njtierney** [comment]
Hi there,

For the vignette, you could make this run faster by changing the number of simulations to be lower, and then reference this in the code that users should run a certain number of simulations.

**Comment by njtierney** [comment]
For reference it took about 5 minutes on my M1 laptop to render the vignette.

**Comment by Tpatni123** [comment]
Thanks for letting me know! I think 5 mins is fine and I am hesitant to reduce the number of simulations as it will change all the results and as a result, the type I and type II errors will not reach the desired level. So, I think the current number of simulations is fine.
